### ISSUE TITLE
Placeholder about socket mode for Slack

### ISSUE THREAD

**Issue by dreeves** [dreeves/lexiguess#94]
## Desiderata

- [x] Jake clarifies what this gissue is actually about
- [x] TBD

_**Verbata**: testing, dev env, dev mode,_

**Comment by jakecoble** [comment]
Slack bots need to serve an endpoint to receive Slack events. This would make development painful, so there's "socket mode" which doesn't have the endpoint requirement. Socket mode is recommended only for development by the documentation for reasons not given.

Lexiguess currently looks for the environment variable `DEBUG` when it starts up. If this variable is set to anything (and environment variables are strings, so I do mean _anything_: even `false`, `0`, etc.), Lexiguess uses socket mode.

In order to use socket mode, however, socket mode must be toggled on in the app's configuration https://app.slack.com/app-settings/T0HC65LRM/A011Z3TQ7BK/socket-mode

In order to use socket mode locally, you have to both set `DEBUG` in your environment and make sure socket mode is turned on in the configuration. This will likely cause live instances of Lexiguess to fail on Slack. When you're finished testing locally, you'll need to make sure to turn socket mode off again.

https://api.slack.com/apis/connections/socket

**Comment by dreeves** [comment]
Thanks! Makes sense (I think). Shall we just move this to the README and call this done?
